const state = { tags: ['탐구 설계', '자료 분석'], current: null, records: [
  { id: '20417', grade: '2학년', subject: '생명과학', title: '효소의 온도에 따른 반응 속도 탐구', date: '2026.07.24', text: '효소의 온도에 따른 반응 속도 탐구에서 독립 변인과 통제 변인을 구분하여 실험 조건을 설정하고 반복 측정을 통해 자료의 신뢰도를 높이고자 함. 예상과 다른 결과가 나타나자 측정 과정과 시료 조건을 점검하며 오차 원인을 분석하고 실험 방법을 수정하는 태도를 보임. 수집한 결과를 비교하여 온도가 일정 수준을 넘을 때 효소의 반응 속도가 감소하는 양상을 해석하고, 변인 통제 능력과 자료 해석 능력이 드러남.' },
  { id: '10312', grade: '1학년', subject: '수학', title: '함수 모델링 프로젝트', date: '2026.07.19', text: '실생활 자료를 함수로 모델링하는 과정에서 변수 간 관계를 표와 그래프로 비교하고, 적절한 모델을 선택한 근거를 설명함. 피드백을 반영하여 해석의 범위를 수정하며 수학적 의사소통 역량을 보임.' },
  { id: '20508', grade: '2학년', subject: '화학', title: '산·염기 중화 반응 토론', date: '2026.07.11', text: '중화 반응의 입자 관점에 관한 토론에서 자료의 출처를 확인하고 주장과 근거를 구분하여 의견을 제시함. 다른 관점을 들은 뒤 설명을 보완하며 개념을 정확하게 표현하려는 태도가 드러남.' }
]};
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400); }
function nav(view) { $$('.nav-item').forEach(x => x.classList.toggle('active', x.dataset.view === view)); $$('.view').forEach(x => x.classList.remove('active-view')); $(`#${view}-view`).classList.add('active-view'); if (view === 'history') renderHistory(); }
$$('[data-view]').forEach(b => b.addEventListener('click', () => nav(b.dataset.view)));
function renderTags() { $('#tags').innerHTML = state.tags.map((t, i) => `<span class="tag">${t}<button type="button" data-remove="${i}">×</button></span>`).join(''); $$('[data-remove]').forEach(b => b.onclick = () => { state.tags.splice(+b.dataset.remove, 1); renderTags(); }); }
renderTags();
$('#keywordInput').addEventListener('keydown', e => { if (e.key === 'Enter' && e.target.value.trim()) { state.tags.push(e.target.value.trim()); e.target.value = ''; renderTags(); e.preventDefault(); } });
$$('[data-tag]').forEach(b => b.onclick = () => { if (!state.tags.includes(b.dataset.tag)) { state.tags.push(b.dataset.tag); renderTags(); } });
$('#observation').addEventListener('input', e => $('#charCount').textContent = `${e.target.value.length}자`);
function makeDraft() { const subject = $('#subject').value, grade = `${$('#grade').value}학년`, title = $('#activityTitle').value.trim(), obs = $('#observation').value.trim(), result = $('#result').value.trim(), resolution = $('#resolution').value.trim(); let text = `${title}에서 ${state.tags.join(', ')}을(를) 중심으로 활동함. ${obs}`; if (result) text += ` 그 결과 ${result}을(를) 확인하고 자료를 바탕으로 해석함.`; if (resolution) text += ` 과정에서 ${resolution}하며 탐구 내용을 보완하는 태도를 보임.`; text += ` 활동 과정에서 구체적인 근거를 바탕으로 사고를 전개하며 ${subject} 교과 역량이 드러남.`; return { studentId: $('#studentId').value || '미입력', grade, subject, title, date: new Date().toLocaleDateString('ko-KR'), text: text.replaceAll('최고', '중요한').replaceAll('완벽하게', '꼼꼼하게') }; }
$('#record-form').addEventListener('submit', e => { e.preventDefault(); if (!$('#activityTitle').value.trim() || !$('#observation').value.trim()) { toast('활동명과 관찰 내용을 입력해주세요.'); return; } const d = makeDraft(); state.current = d; $('#resultStudent').textContent = d.studentId; $('#resultGrade').textContent = d.grade; $('#resultSubject').textContent = d.subject; $('#resultDate').textContent = d.date; $('#draftSubject').textContent = d.subject; $('#draftText').textContent = d.text; $('#agentLog').innerHTML = ['수집 에이전트 · 입력 정리 완료', '작성 에이전트 · 초안 작성 완료', '검토 에이전트 · 표현 점검 완료'].map(x => `<span class="log-chip done">✓ ${x}</span>`).join(''); nav('result'); });
$('#backBtn').onclick = () => nav('write');
$('#copyBtn').onclick = () => navigator.clipboard?.writeText($('#draftText').textContent).then(() => toast('초안을 클립보드에 복사했습니다.'));
$('#downloadBtn').onclick = () => { const d = state.current, blob = new Blob([`[${d.subject} 세부능력 및 특기사항]\n\n${d.text}`], { type: 'text/plain;charset=utf-8' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `${d.studentId}_${d.subject}_세특.txt`; a.click(); URL.revokeObjectURL(a.href); };
const defaultSupabase = window.RECORDGYEOL_SUPABASE || {};
const supabaseUrl = () => localStorage.getItem('recordgyeol_supabaseUrl') || defaultSupabase.url;
const supabaseKey = () => localStorage.getItem('recordgyeol_supabaseKey') || defaultSupabase.key;
async function supabaseRequest(path, options = {}) { const url = supabaseUrl(), key = supabaseKey(); if (!url || !key) return null; const res = await fetch(`${url}/rest/v1/${path}`, { ...options, headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', Prefer: 'return=representation', ...(options.headers || {}) } }); if (!res.ok) throw new Error(`Supabase ${res.status}`); return res.status === 204 ? null : res.json(); }
async function loadSupabase() { try { const rows = await supabaseRequest('se_teuk_records?select=student_identifier,grade,subject,activity_title,draft_text,created_at&order=created_at.desc&limit=30'); if (rows?.length) { state.records = rows.map(r => ({ id: r.student_identifier, grade: `${r.grade}학년`, subject: r.subject, title: r.activity_title, date: new Date(r.created_at).toLocaleDateString('ko-KR'), text: r.draft_text })); renderHistory(); } } catch (e) { toast('Supabase 조회에 실패해 로컬 기록을 보여드립니다.'); } }
$('#saveBtn').onclick = async () => { if (!state.current) return; const d = state.current; try { await supabaseRequest('se_teuk_records', { method: 'POST', body: JSON.stringify({ student_identifier: d.studentId, grade: Number(d.grade[0]), subject: d.subject, activity_title: d.title, input_payload: { keywords: state.tags, observation: $('#observation').value }, draft_text: d.text, review_notes: [{ status: 'checked' }], model: localStorage.getItem('recordgyeol_model') || 'Gemini 3.5 Flash-Lite' }) }); } catch (e) { toast('DB 연결이 없어 로컬에 보관합니다.'); } state.records.unshift(d); localStorage.setItem('recordgyeol_records', JSON.stringify(state.records)); toast('저장 내역에 추가했습니다.'); $('#saveBtn').textContent = '저장 완료 ✓'; };
function renderHistory() { const q = ($('#searchInput')?.value || '').toLowerCase(), rows = state.records.filter(r => [r.id, r.subject, r.title].join(' ').toLowerCase().includes(q)); $('#historyCount').textContent = `${rows.length}개 기록`; $('#historyList').innerHTML = rows.map(r => `<article class="history-item"><div><h3>${r.title}</h3><p>${r.id} · ${r.date}</p></div><div class="history-meta">학년<b>${r.grade}</b></div><div class="history-meta">과목<b>${r.subject}</b></div><button class="history-open" data-history="${r.id}">다시 보기 →</button></article>`).join('') || '<p>아직 저장된 내역이 없습니다.</p>'; $$('[data-history]').forEach(b => b.onclick = () => { const d = state.records.find(r => r.id === b.dataset.history); state.current = d; $('#resultStudent').textContent = d.id; $('#resultGrade').textContent = d.grade; $('#resultSubject').textContent = d.subject; $('#resultDate').textContent = d.date; $('#draftSubject').textContent = d.subject; $('#draftText').textContent = d.text; nav('result'); }); }
$('#searchInput').addEventListener('input', renderHistory); const saved = localStorage.getItem('recordgyeol_records'); if (saved) state.records = JSON.parse(saved);
$('#settingsSave').onclick = () => { localStorage.setItem('recordgyeol_apiKey', $('#apiKey').value); localStorage.setItem('recordgyeol_model', $('#modelSelect').value); $('#connectionBadge').textContent = $('#apiKey').value ? '연결됨' : '데모 모드'; toast('개인 설정을 저장했습니다.'); };
$('#apiKey').value = localStorage.getItem('recordgyeol_apiKey') || ''; $('#modelSelect').value = localStorage.getItem('recordgyeol_model') || 'Gemini 3.5 Flash-Lite';
if (supabaseUrl() && supabaseKey()) loadSupabase();

