const state = { tags: ['?먭뎄 ?ㅺ퀎', '?먮즺 遺꾩꽍'], current: null, records: [
  { id: '20417', grade: '2?숇뀈', subject: '?앸챸怨쇳븰', title: '?⑥냼???⑤룄???곕Ⅸ 諛섏쓳 ?띾룄 ?먭뎄', date: '2026.07.24', text: '?⑥냼???⑤룄???곕Ⅸ 諛섏쓳 ?띾룄 ?먭뎄?먯꽌 ?낅┰ 蹂?멸낵 ?듭젣 蹂?몄쓣 援щ텇?섏뿬 ?ㅽ뿕 議곌굔???ㅼ젙?섍퀬 諛섎났 痢≪젙???듯빐 ?먮즺???좊ː?꾨? ?믪씠怨좎옄 ?? ?덉긽怨??ㅻⅨ 寃곌낵媛 ?섑??섏옄 痢≪젙 怨쇱젙怨??쒕즺 議곌굔???먭??섎ŉ ?ㅼ감 ?먯씤??遺꾩꽍?섍퀬 ?ㅽ뿕 諛⑸쾿???섏젙?섎뒗 ?쒕룄瑜?蹂댁엫. ?섏쭛??寃곌낵瑜?鍮꾧탳?섏뿬 ?⑤룄媛 ?쇱젙 ?섏????섏쓣 ???⑥냼??諛섏쓳 ?띾룄媛 媛먯냼?섎뒗 ?묒긽???댁꽍?섍퀬, 蹂???듭젣 ?λ젰怨??먮즺 ?댁꽍 ?λ젰???쒕윭??' },
  { id: '10312', grade: '1?숇뀈', subject: '?섑븰', title: '?⑥닔 紐⑤뜽留??꾨줈?앺듃', date: '2026.07.19', text: '?ㅼ깮???먮즺瑜??⑥닔濡?紐⑤뜽留곹븯??怨쇱젙?먯꽌 蹂??媛?愿怨꾨? ?쒖? 洹몃옒?꾨줈 鍮꾧탳?섍퀬, ?곸젅??紐⑤뜽???좏깮??洹쇨굅瑜??ㅻ챸?? ?쇰뱶諛깆쓣 諛섏쁺?섏뿬 ?댁꽍??踰붿쐞瑜??섏젙?섎ŉ ?섑븰???섏궗?뚰넻 ??웾??蹂댁엫.' },
  { id: '20508', grade: '2?숇뀈', subject: '?뷀븰', title: '?걔룹뿼湲?以묓솕 諛섏쓳 ?좊줎', date: '2026.07.11', text: '以묓솕 諛섏쓳???낆옄 愿?먯뿉 愿???좊줎?먯꽌 ?먮즺??異쒖쿂瑜??뺤씤?섍퀬 二쇱옣怨?洹쇨굅瑜?援щ텇?섏뿬 ?섍껄???쒖떆?? ?ㅻⅨ 愿?먯쓣 ?ㅼ? ???ㅻ챸??蹂댁셿?섎ŉ 媛쒕뀗???뺥솗?섍쾶 ?쒗쁽?섎젮???쒕룄媛 ?쒕윭??' }
]};
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400); }
function nav(view) { $$('.nav-item').forEach(x => x.classList.toggle('active', x.dataset.view === view)); $$('.view').forEach(x => x.classList.remove('active-view')); $(`#${view}-view`).classList.add('active-view'); if (view === 'history') renderHistory(); }
$$('[data-view]').forEach(b => b.addEventListener('click', () => nav(b.dataset.view)));
function renderTags() { $('#tags').innerHTML = state.tags.map((t, i) => `<span class="tag">${t}<button type="button" data-remove="${i}">횞</button></span>`).join(''); $$('[data-remove]').forEach(b => b.onclick = () => { state.tags.splice(+b.dataset.remove, 1); renderTags(); }); }
renderTags();
$('#keywordInput').addEventListener('keydown', e => { if (e.key === 'Enter' && e.target.value.trim()) { state.tags.push(e.target.value.trim()); e.target.value = ''; renderTags(); e.preventDefault(); } });
$$('[data-tag]').forEach(b => b.onclick = () => { if (!state.tags.includes(b.dataset.tag)) { state.tags.push(b.dataset.tag); renderTags(); } });
$('#observation').addEventListener('input', e => $('#charCount').textContent = `${e.target.value.length}??);
function makeDraft() { const subject = $('#subject').value, grade = `${$('#grade').value}?숇뀈`, title = $('#activityTitle').value.trim(), obs = $('#observation').value.trim(), result = $('#result').value.trim(), resolution = $('#resolution').value.trim(); let text = `${title}?먯꽌 ${state.tags.join(', ')}??瑜? 以묒떖?쇰줈 ?쒕룞?? ${obs}`; if (result) text += ` 洹?寃곌낵 ${result}??瑜? ?뺤씤?섍퀬 ?먮즺瑜?諛뷀깢?쇰줈 ?댁꽍??`; if (resolution) text += ` 怨쇱젙?먯꽌 ${resolution}?섎ŉ ?먭뎄 ?댁슜??蹂댁셿?섎뒗 ?쒕룄瑜?蹂댁엫.`; text += ` ?쒕룞 怨쇱젙?먯꽌 援ъ껜?곸씤 洹쇨굅瑜?諛뷀깢?쇰줈 ?ш퀬瑜??꾧컻?섎ŉ ${subject} 援먭낵 ??웾???쒕윭??`; return { studentId: $('#studentId').value || '誘몄엯??, grade, subject, title, date: new Date().toLocaleDateString('ko-KR'), text: text.replaceAll('理쒓퀬', '以묒슂??).replaceAll('?꾨꼍?섍쾶', '瑗쇨세?섍쾶') }; }
$('#record-form').addEventListener('submit', e => { e.preventDefault(); if (!$('#activityTitle').value.trim() || !$('#observation').value.trim()) { toast('?쒕룞紐낃낵 愿李??댁슜???낅젰?댁＜?몄슂.'); return; } const d = makeDraft(); state.current = d; $('#resultStudent').textContent = d.studentId; $('#resultGrade').textContent = d.grade; $('#resultSubject').textContent = d.subject; $('#resultDate').textContent = d.date; $('#draftSubject').textContent = d.subject; $('#draftText').textContent = d.text; $('#agentLog').innerHTML = ['?섏쭛 ?먯씠?꾪듃 쨌 ?낅젰 ?뺣━ ?꾨즺', '?묒꽦 ?먯씠?꾪듃 쨌 珥덉븞 ?묒꽦 ?꾨즺', '寃???먯씠?꾪듃 쨌 ?쒗쁽 ?먭? ?꾨즺'].map(x => `<span class="log-chip done">??${x}</span>`).join(''); nav('result'); });
$('#backBtn').onclick = () => nav('write');
$('#copyBtn').onclick = () => navigator.clipboard?.writeText($('#draftText').textContent).then(() => toast('珥덉븞???대┰蹂대뱶??蹂듭궗?덉뒿?덈떎.'));
$('#downloadBtn').onclick = () => { const d = state.current, blob = new Blob([`[${d.subject} ?몃??λ젰 諛??밴린?ы빆]\n\n${d.text}`], { type: 'text/plain;charset=utf-8' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `${d.studentId}_${d.subject}_?명듅.txt`; a.click(); URL.revokeObjectURL(a.href); };
const defaultSupabase = window.RECORDGYEOL_SUPABASE || {};
const supabaseUrl = () => localStorage.getItem('recordgyeol_supabaseUrl') || defaultSupabase.url;
const supabaseKey = () => localStorage.getItem('recordgyeol_supabaseKey') || defaultSupabase.key;
async function supabaseRequest(path, options = {}) { const url = supabaseUrl(), key = supabaseKey(); if (!url || !key) return null; const res = await fetch(`${url}/rest/v1/${path}`, { ...options, headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', Prefer: 'return=representation', ...(options.headers || {}) } }); if (!res.ok) throw new Error(`Supabase ${res.status}`); return res.status === 204 ? null : res.json(); }
async function loadSupabase() { try { const rows = await supabaseRequest('se_teuk_records?select=student_identifier,grade,subject,activity_title,draft_text,created_at&order=created_at.desc&limit=30'); if (rows?.length) { state.records = rows.map(r => ({ id: r.student_identifier, grade: `${r.grade}?숇뀈`, subject: r.subject, title: r.activity_title, date: new Date(r.created_at).toLocaleDateString('ko-KR'), text: r.draft_text })); renderHistory(); } } catch (e) { toast('Supabase 議고쉶???ㅽ뙣??濡쒖뺄 湲곕줉??蹂댁뿬?쒕┰?덈떎.'); } }
$('#saveBtn').onclick = async () => { if (!state.current) return; const d = state.current; try { await supabaseRequest('se_teuk_records', { method: 'POST', body: JSON.stringify({ student_identifier: d.studentId, grade: Number(d.grade[0]), subject: d.subject, activity_title: d.title, input_payload: { keywords: state.tags, observation: $('#observation').value }, draft_text: d.text, review_notes: [{ status: 'checked' }], model: localStorage.getItem('recordgyeol_model') || 'Gemini 3.5 Flash-Lite' }) }); } catch (e) { toast('DB ?곌껐???놁뼱 濡쒖뺄??蹂닿??⑸땲??'); } state.records.unshift(d); localStorage.setItem('recordgyeol_records', JSON.stringify(state.records)); toast('????댁뿭??異붽??덉뒿?덈떎.'); $('#saveBtn').textContent = '????꾨즺 ??; };
function renderHistory() { const q = ($('#searchInput')?.value || '').toLowerCase(), rows = state.records.filter(r => [r.id, r.subject, r.title].join(' ').toLowerCase().includes(q)); $('#historyCount').textContent = `${rows.length}媛?湲곕줉`; $('#historyList').innerHTML = rows.map(r => `<article class="history-item"><div><h3>${r.title}</h3><p>${r.id} 쨌 ${r.date}</p></div><div class="history-meta">?숇뀈<b>${r.grade}</b></div><div class="history-meta">怨쇰ぉ<b>${r.subject}</b></div><button class="history-open" data-history="${r.id}">?ㅼ떆 蹂닿린 ??/button></article>`).join('') || '<p>?꾩쭅 ??λ맂 ?댁뿭???놁뒿?덈떎.</p>'; $$('[data-history]').forEach(b => b.onclick = () => { const d = state.records.find(r => r.id === b.dataset.history); state.current = d; $('#resultStudent').textContent = d.id; $('#resultGrade').textContent = d.grade; $('#resultSubject').textContent = d.subject; $('#resultDate').textContent = d.date; $('#draftSubject').textContent = d.subject; $('#draftText').textContent = d.text; nav('result'); }); }
$('#searchInput').addEventListener('input', renderHistory); const saved = localStorage.getItem('recordgyeol_records'); if (saved) state.records = JSON.parse(saved);
$('#settingsSave').onclick = () => { localStorage.setItem('recordgyeol_apiKey', $('#apiKey').value); localStorage.setItem('recordgyeol_model', $('#modelSelect').value); $('#connectionBadge').textContent = $('#apiKey').value ? '?곌껐?? : '?곕え 紐⑤뱶'; toast('媛쒖씤 ?ㅼ젙????ν뻽?듬땲??'); };
$('#apiKey').value = localStorage.getItem('recordgyeol_apiKey') || ''; $('#modelSelect').value = localStorage.getItem('recordgyeol_model') || 'Gemini 3.5 Flash-Lite';
if (supabaseUrl() && supabaseKey()) loadSupabase();

